### ISSUE TITLE
FEATURE : Add encryption option

### ISSUE THREAD

**Issue by Neo-29** [Rawleenc/ArchCraftsman#38]
In English this time 😉.
Is there a way to add encryption option in the script?

**Comment by Rawleenc** [comment]
Hello,  
Currently there is no support for encryption.  
But it's a good idea.  
I'll look into this for the next 3.4.0.

**Comment by Rawleenc** [comment]
Note : 
 [LUKS on a partition](https://wiki.archlinux.org/title/Dm-crypt/Encrypting_an_entire_system#LUKS_on_a_partition) method should be supported only  
Mandatory partitions are un-encrypted /boot and encrypted /root, so need to adapt partitioning systems to include this new mandatory /boot option as EFI partition will NOT be mounted elsewhere than /boot/efi  
Dual boot should be working with an encrypted linux system, need to test

**Comment by Neo-29** [comment]
👏👍👍👍

**Comment by Rawleenc** [comment]
Merged on dev !
