### ISSUE TITLE
FEATURE : Add the possibility to not have any session manager

### ISSUE THREAD

**Issue by Neo-29** [Rawleenc/ArchCraftsman#40]
Hello there 😉

Would it be possible in next or future version to add the choice of lightdm sddm... Etc... for the desktops ( gnome and cinnamon exluded)
Or maybe none?

**Comment by Rawleenc** [comment]
Hi !

The possibility to choose any session manager for any desktop environment is not in accordance with my vision of this script which is to propose a whole coherent base on which I will be susceptible to start from.

But, on the other hand, I'm ok with adding the possibility to not have any session manager, it's a choice I could do.

Are you ok with that ?

**Comment by Neo-29** [comment]
Hello!
That seems good for me!
As one could easily choose the DM wanted afterall.... 
The thing I had in mind was to let the choice so.. Good 👍
The only thing is the user doesn't know which DE is chosen ( except for gnome and gdm)
For example I don't know which one uses lightdm for example...

Do you see what I mean?

**Comment by Rawleenc** [comment]
Hmm yes I see, maybe specifying the couple DE/SM for each environment ?

**Comment by Neo-29** [comment]
Yeahhh.. Could be great! Maybe with a ?  Help specifying something like
If you want another DM choose none and install it yourself when finished 😂😂😂
Joke apart your idea is very good

**Comment by Rawleenc** [comment]
Feature implemented in dev branch. It is now possible to not install the display manager for all environment that not include one as dependencies.
