### ISSUE TITLE
Branche dev 404 not found

### ISSUE THREAD

**Issue by Neo-29** [Rawleenc/ArchCraftsman#42]
Impossible de récupérer la branche dev par curl (aidev)

**Comment by Neo-29** [comment]
Working now

**Comment by Rawleenc** [comment]
@Neo-29 Yes, I proceeded to an identity change for the script :)

**Comment by Neo-29** [comment]
I saw the change 😉. Problem with archlinux trademark?

**Comment by Rawleenc** [comment]
Nop, I just wanted to reinforce its identity, to make it more distinctive and to carry an idea that I like for this project: 
A script to install a carefully handcrafted Archlinux :)

**Comment by Neo-29** [comment]
👏👏👍
