### ISSUE TITLE
BUGFIX : ttf-nerd-fonts-symbols package is not available

### ISSUE THREAD

**Issue by shiioo** [Rawleenc/ArchCraftsman#43]
Just a small issue but which prevents the script to proceed if you pick the option to add more fonts.

**Comment by Neo-29** [comment]
https://archlinux.org/packages/community/any/ttf-nerd-fonts-symbols/

Here are all the packages avalaible.
Yours is not " complete"
I think this is the reason why it fails here.

**Comment by Rawleenc** [comment]
Fixed in 3.3.3. Thanks for the report !
