### ISSUE TITLE
FEATURE : Uniformize the way bundles are managed

### ISSUE THREAD

**Issue by Rawleenc** [Rawleenc/ArchCraftsman#45]
Create a bundle blueprint with `packages` method to retreived all packages of the bundle and a `configure` method to execute all mandatory configuration for the bundle.

Use this system for desktop environment, for linux kernels **(add support for zen and hardened kernels)**, for bootloaders, for microcodes and for all options.

Uniformize the way bundles are prompted with a `prompt_bundle` method.
Add a factory method to get the proper bundle by name.

**Comment by Neo-29** [comment]
Ça bosse dur👏👏😉
