### ISSUE TITLE
BUGFIX : SD Card partitions not properly recognized when auto-partitioning

### ISSUE THREAD

**Issue by shiioo** [Rawleenc/ArchCraftsman#47]
Installed Arch on a laptop that only used a SD card as its main storage space and it was recognized as `/dev/mmcblk1`.
Once the installation started, the script halted as there was apparently not enough space to proceed.
Scrolling up, errors about partitions not being mounted were reported.

I then went through manual partitioning and everything went well.

When letting the script handle the work, it looked for these partitions: `/dev/mmcblk11`, `/dev/mmcblk12`, `/dev/mmcblk13` and `/dev/mmcblk14`.
When doing the partitions manually, the script looked for these instead: `/dev/mmcblk1p1`, `/dev/mmcblk1p2`, `/dev/mmcblk1p3` and `/dev/mmcblk1p4`, which were the correct names.

Just a missing `p` =)

**Comment by Rawleenc** [comment]
Note to fix this issue : Use the `lsblk -J` command result in a dict in the `build_partition_name` method to find the real partition name in all cases.

**Comment by Rawleenc** [comment]
Issue fixed in development branch, tested on an nvme disk with partition names like `nvme0n1p1`.
