### ISSUE TITLE
ISSUE: Pacstrap -K option doesn't exist on Archiso < 2022.10.01

### ISSUE THREAD

**Issue by Neo-29** [Rawleenc/ArchCraftsman#49]
Hello,
I faced this issue trying the main and dev version
![image](https://user-images.githubusercontent.com/90937180/198895414-f2eae1c7-ca90-4c0e-a4ab-d3b0df41bed3.png)

![image](https://user-images.githubusercontent.com/90937180/198895714-f3bff0ec-b51e-4dfb-b6f1-837778f55ccb.png)

**Comment by Rawleenc** [comment]
Hello, I'm unable to reproduce on the latest ISO, the -K option of Pacstrap is maybe very new, are you using the latest october Arch ISO ?

**Comment by Neo-29** [comment]
Mmmm.. This one is September I think.

**Comment by Rawleenc** [comment]
Try with the October ISO, it should work without issues.

**Comment by Rawleenc** [comment]
-K option has been added in this commit https://github.com/archlinux/arch-install-scripts/commit/8be93400011fa45dd4048707c7bfa8bdc2cb3202

So it has been integrated in the v27 of pacstrap which as been release on Septembre 28.

**Comment by Neo-29** [comment]
> -K option has been added in this commit [archlinux/arch-install-scripts@8be9340](https://github.com/archlinux/arch-install-scripts/commit/8be93400011fa45dd4048707c7bfa8bdc2cb3202)
> 
> So it has been integrated in the v27 of pacstrap which as been release on Septembre 28.

That's probably the reason...
I'm quite fed up with archiso changes...
Too much.
And the pb is if someone wants to use your script, he won't be able if not the last iso here.
This is not your problem in fact...
This is linked to archiso.
I'll retry when I can with last iso

**Comment by Rawleenc** [comment]
> > -K option has been added in this commit [archlinux/arch-install-scripts@8be9340](https://github.com/archlinux/arch-install-scripts/commit/8be93400011fa45dd4048707c7bfa8bdc2cb3202)
> > 
> > So it has been integrated in the v27 of pacstrap which as been release on Septembre 28.
> 
> That's probably the reason...
> I'm quite fed up with archiso changes...
> Too much.
> And the pb is if someone wants to use your script, he won't be able if not the last iso here.
> This is not your problem in fact...
> This is linked to archiso.
> I'll retry when I can with last iso 

Yes I understand that it's a quite engaging change but the gain is too much important to keep the first keyring workaround.
And moreover, it's generally a good practice to maintain the archlinux installation medium up to date. :)

**Comment by Neo-29** [comment]
Can you explain (quickly) what it does?
Because I faced up too much problem with `pacman  - - init service` layency lately.
Does it quite solve this problem? Or nothing to do with it 🤔

**Comment by Rawleenc** [comment]
This option allow to initialize an empty archlinux keyring on the new system, this fix the issue "key not found" in certain case when you install late in the month.

To fix this before this new option I added a whole new step to reinstall archlinux keyring on the new system right after the pacstrap step.

This worked, but it was quite slow and not very satisfying for me.

With this new option the new system got a brand fresh keyring so no issues and I can remove my previous workaround to gain a quite big amount of time on the execution 😁

**Comment by Neo-29** [comment]
Nice!

**Comment by Neo-29** [comment]
Solved with latest version of archiso
