### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Neo-29** [Rawleenc/ArchCraftsman#50]
Fail with new arch iso

here' s the picture
![image](https://user-images.githubusercontent.com/90937180/207140420-80778e38-c400-4e28-915a-8a14feacf5d4.png)

auto partitionning
ext4
plasma with wayland
efi

**Comment by Rawleenc** [comment]
Hello !
Should be fixed in dev branch.

**Comment by Neo-29** [comment]
> Hello ! Should be fixed in dev branch.

Now that....
And I have 20G allocated
![image](https://user-images.githubusercontent.com/90937180/207973316-d9f2c013-c8f4-4708-b569-cb397bf6b8c3.png)

**Comment by Neo-29** [comment]
Here's what has been done using auto partitionning
![image](https://user-images.githubusercontent.com/90937180/207973920-64866aec-d696-49da-a874-2685226c7bf5.png)

**Comment by Neo-29** [comment]
Working the second time

Closing the issue.

Don't know what happened
