### ISSUE TITLE
Failure on keys with latest iso 

### ISSUE THREAD

**Issue by Neo-29** [Rawleenc/ArchCraftsman#51]
![image](https://user-images.githubusercontent.com/90937180/207975809-fb385039-90e6-4bc7-88de-bb4c42739da9.png)

Fed up with those keyring errors on arch lol...

Maybe something to adjust in the script?

![image](https://user-images.githubusercontent.com/90937180/207975949-4e1a979e-d1f0-4e1d-9fbf-d718894a2c96.png)

**Comment by Neo-29** [comment]
Retried today.
No pb...
Well.... Arch is arch 😉

**Comment by Rawleenc** [comment]
Hello !
Was about to test this tonight but yes, maybe an ponctual problem with archlinux-keyring 🤷

Glad to know that it finally worked without changing anything 😁

**Comment by Neo-29** [comment]
![image](https://user-images.githubusercontent.com/90937180/208907826-6414f392-2108-42d2-b30c-984859cab8ad.png)

**Comment by Rawleenc** [comment]
Hello, I experienced this yesterday, I figured out that running `pacman -Sy --needed archlinux-keyring` before `pacstrap -K` command to install the base fix this issue. So I pushed a commit to integrate this fix on dev branch. Are you using the dev branch with the latest archlinux iso ?

**Comment by Neo-29** [comment]
> Hello, I experienced this yesterday, I figured out that running `pacman -Sy --needed archlinux-keyring` before `pacstrap -K` command to install the base fix this issue. So I pushed a commit to integrate this fix on dev branch. Are you using the dev branch with the latest archlinux iso ?

Yes. Last version of archlinux and dev version of your script.

**Comment by Rawleenc** [comment]
I'm forced to reintroduce the archlinux-keyring update step I removed with the -K option of pacstrap.  
I'm also forced to keep the archlinux-keyring update step of the live ISO system I added yesterday because without it there is a GPG error with openssl package, installed with basic pacstrap /mnt base linux linux-firmware...  
Two long steps to only manage a keyring is really a pain...
But no choice.

**Comment by Neo-29** [comment]
> 

Yes.
No pain.. No gain... 😉.

**Comment by Rawleenc** [comment]
Should be fixed on dev

**Comment by Neo-29** [comment]
> Should be fixed on dev

Want me to check?

**Comment by Rawleenc** [comment]
When you'll get time :)

**Comment by Neo-29** [comment]
> When you'll get time :)

Working!
