### ISSUE TITLE
BUGFIX: Fix automatic partitioning

### ISSUE THREAD

**Issue by Rawleenc** [Rawleenc/ArchCraftsman#54]
The automatic partitioning system is not working in case of no partitions present on the target disk.

The issue is with the build_partition_name method, the current implementation only work if partition already exist (lsblk -J searching for childrens), need to change this.

**Comment by Neo-29** [comment]
Can confirm this!
👍

**Comment by Rawleenc** [comment]
Fixed on dev. I still need to recheck the dualboot support before closing this.

**Comment by Rawleenc** [comment]
Multi boot work fine ! 👍

**Comment by Neo-29** [comment]
> 

Nice!
