### ISSUE TITLE
Installer crashes when creating a swap partition.

### ISSUE THREAD

**Issue by FredBezies** [Rawleenc/ArchCraftsman#56]
Hello.

I tried the last development version in qemu and I noticed a crash in partition step. If I asked for a separate swap partition, I got a crash.

I'm adding a screenshot of the bug.

![Screenshot_archlinux_2023-01-29_21:15:19](https://user-images.githubusercontent.com/8571419/215353595-59526961-c612-494d-8d28-04b8829be325.png)

**Comment by Rawleenc** [comment]
Hello @FredBezies, thanks for the report.
This issue has been fixed in the dev branch.

**Comment by Rawleenc** [comment]
I've also fixed the main stable branch accordingly
