### ISSUE TITLE
IP static configuration not saved

### ISSUE THREAD

**Issue by flopal** [Rawleenc/ArchCraftsman#57]
Before run script, I setup my IP configuration with static method with this parameters:
```
Physical interface : ens18
My IP              : 192.168.100.8/24
My gateway         : 192.168.100.1
```
I run this commands:
```
ip addr add 192.168.100.8/24 dev ens18
ip route add default via 192.168.100.1 dev ens18
```

And setup /etc/resolv.conf as follow:
```
search lan
nameserver 192.168.100.1
```
After installation and reboot, the IP configuration was lost and I needed to redo the configuration.
Can you add support for IP static configuration ?

**Comment by Rawleenc** [comment]
Hello @flopal, a first step to implement something for this issue has been pushed on dev : An option to choose the network stack to install/activate.

**Comment by Rawleenc** [comment]
The new network stack option allow to choose systemd as network stack. By choosing this option, ArchCraftsman will copy archiso configuration files to make things automatically working as soon as the new system starts up. So you can get your network copied by editing archiso config file and restarting systemd-networkd and systemd-resolved before launching ArchCraftsman
