### ISSUE TITLE
4.0 : Arch Craftsman full automation update

### ISSUE THREAD

**Issue by Rawleenc** [Rawleenc/ArchCraftsman#58]
This issue describe the core feature of the next 4.0.0 major update :
* The objective is to make Arch Craftsman able to take a configuration file to fully automate all user interactions.
* See the following PR for details : [https://github.com/Rawleenc/ArchCraftsman/pull/65](https://github.com/Rawleenc/ArchCraftsman/pull/65)

**Comment by Neo-29** [comment]
👍👍👏👏

**Comment by Rawleenc** [comment]
Full automation update is now available on dev branch.

Remaining to be done : 
- [ ] Update README to add a section about automation
