### ISSUE TITLE
Fail to install with encryption on root

### ISSUE THREAD

**Issue by Neo-29** [Rawleenc/ArchCraftsman#60]
I tried dev version
auto partitionning
qemu/virtmanager
/dev/vda with encryption on root
version archlinux-2023.02.01-x86_64.iso

 here's  the result

![pb crypt rawleenc](https://user-images.githubusercontent.com/90937180/221557201-4d9c4dc3-bb64-4f9c-b915-0da60e5e8f08.png)

**Comment by Rawleenc** [comment]
Hello, you need to type yes in uppercase as described

**Comment by Neo-29** [comment]
Zut.. Lol. Pas bien. Vu. 
Ça devrait presque être bloquant 🤣😉

**Comment by Neo-29** [comment]
Install successfull with encryption 
No issues to report.
Perfect.

**Comment by Rawleenc** [comment]
I don't have the possibility to change these prompts as it's prompts of the cryptsetup command itself, not prompts of archcraftsman

**Comment by Neo-29** [comment]
> I don't have the possibility to change these prompts as it's prompts of the cryptsetup command itself, not prompts of archcraftsman

👍
