### ISSUE TITLE
Enhancement?

### ISSUE THREAD

**Issue by Neo-29** [Rawleenc/ArchCraftsman#61]
![image](https://user-images.githubusercontent.com/90937180/221559424-3209c9f4-b85d-49d1-8626-1599e9e47ea8.png)
In fact here the cursor is blinking unless we strike ENTER key

If we don't know ... we can think we have to wait for something to happen.

Maybe "confirm thing"?

**Comment by Rawleenc** [comment]
Not sure what to do here, maybe a little prompt character like `> ` at the beginning of the new line ?

**Comment by Neo-29** [comment]
> Not sure what to do here, maybe a little prompt character like `> ` at the beginning of the new line ?

Yes, that can work.
Or something like " strike enter if correct"?

**Comment by Rawleenc** [comment]
No it's too long. New line prompt are for potentially long input to manage issues in small resolution screens like try for example.
I will add a prompt character just like the shell mode

**Comment by Neo-29** [comment]
> No it's too long. New line prompt are for potentially long input to manage issues in small resolution screens like try for example. I will add a prompt character just like the shell mode

👍👍👍

**Comment by Rawleenc** [comment]
Pushed on dev
