### ISSUE TITLE
Fail to select the good locale ( lxqt) 

### ISSUE THREAD

**Issue by Neo-29** [Rawleenc/ArchCraftsman#67]
I followed as usual the steps.
System is in English. Strange.
Lxqt desktop with encryption.
Maybe the installer didn´t pick the locale or I missed a step

**Comment by Rawleenc** [comment]
Also fixed and dev, thanks for the report :+1:

**Comment by Rawleenc** [comment]
Hello, I tried with both automated and interactive way with french language and I'm not able to get a system that is not in french. Are you sure you've selected french language ?

**Comment by Neo-29** [comment]
> Hello, I tried with both automated and interactive way with french language and I'm not able to get a system that is not in french. Are you sure you've selected french language ?

Well I must say I have to retry to check that.
I'll let you know.

**Comment by Neo-29** [comment]
Same pb.
The only spot to select French is at the beginning. 
So.... I'm stuck. 
I select us keyboard < mine is US>
All auto 
I get LC ALL unset during install 
Don't know if that can help. 
Locale generated is US only
I tried 3 times

**Comment by Neo-29** [comment]
I insisted ( I like to undersrand when something goes wrong)
The issue was :the ISO... Old from January.
Maybe something in it causing the pb. 

So, of course retried with latest one....
All good!

So... What happened is and will be a mystery to me.
