### ISSUE TITLE
Fail to load module installer on main

### ISSUE THREAD

**Issue by Neo-29** [Rawleenc/ArchCraftsman#69]
![image](https://user-images.githubusercontent.com/90937180/233050213-e34b90ee-2faf-492b-888e-76b8032c59e4.png)

one module seems to fail

main

**Comment by Rawleenc** [comment]
Hello, did you try to relaunch the installer ? Sometimes network issues can lead to some files not downloaded

**Comment by Neo-29** [comment]
Will test later if it's same issue as #70
I'll reopen if needed

**Comment by Rawleenc** [comment]
There may be an issue with the python api used by the launcher to download files. I'll check for it.
