### ISSUE TITLE
Fail to start install on dev (lxqt module?)

### ISSUE THREAD

**Issue by Neo-29** [Rawleenc/ArchCraftsman#70]
![image](https://user-images.githubusercontent.com/90937180/233050895-4fedfded-668a-4fad-a949-7a79d864864d.png)

**Comment by Rawleenc** [comment]
Hello, did you try to relaunch the installer ? Sometimes network issues can lead to some files not downloaded

**Comment by Neo-29** [comment]
> Hello, did you try to relaunch the installer ? Sometimes network issues can lead to some files not downloaded

Retried
Same thing different bundle (mate)

**Comment by Neo-29** [comment]
Second time it works now.

My internet connection is good. Strange.
But now OK
