### ISSUE TITLE
links not available with python

### ISSUE THREAD

**Issue by Neo-29** [Rawleenc/ArchCraftsman#77]
![image](https://github.com/Rawleenc/ArchCraftsman/assets/90937180/acee0ee6-9766-4df4-ba19-5f7231c7cc6e)

**Comment by Rawleenc** [comment]
rotf.lol url of tinyurl.com shortener has been terminated.

And I don't like tinyurl.com base url.

So I fixed this issue by adding my own redirection on my own server.
