### ISSUE TITLE
Fail on install No Module named tomlib 

### ISSUE THREAD

**Issue by Neo-29** [Rawleenc/ArchCraftsman#78]
![image](https://github.com/Rawleenc/ArchCraftsman/assets/90937180/ef67641f-2a30-43e2-ba88-cfa803cd9363)

Tried on main and dev

Same issue

**Comment by Rawleenc** [comment]
@Neo-29 This is because you're not on the latest archlinux iso.

Please update your archiso and try again.

**Comment by Neo-29** [comment]
> @Neo-29 This is because you're not on the latest archlinux iso.
> 
> Please update your archiso and try again.

Omg.. Again...
I forgot that.
