### ISSUE TITLE
System fails to boot. No grub

### ISSUE THREAD

**Issue by Neo-29** [Rawleenc/ArchCraftsman#79]
Hello.

Something strange here.
I installed the system to test ( here xfce) with dev version of the script.
Strangely no boot no grub entry in uefi settings

I decided to chroot. Reinstall grub with id grub =GRUB as per wiki.
It worked. 

I checked `/boot/efi/EFI ` inside I had a folder `Arch Linux` ( made during install) with space between Arch and Linux.

I think this could be the issue.? 

Have you faced something similar? 

Tks

**Comment by Rawleenc** [comment]
Hello, tried an installation on a VM. Nothing wrong happens. System installed and booted without any issues.

Could you please give me more informations on your installation ? VM or hardware, all options you chose, etc.

**Comment by Rawleenc** [comment]
For information, the EFI entry created by ArchCraftsman has always been named `Arch Linux`. So I doubt your issue came from here.

**Comment by Neo-29** [comment]
Was on virtmanager.
Chose auto partitioning
Ext4
No swap
No separate home

**Comment by Rawleenc** [comment]
Strange. I installed almost exactly same way. Could you retry same way to see if you encounter the same issue two times in a raw ?

**Comment by Neo-29** [comment]
> Strange. I installed almost exactly same way. Could you retry same way to see if you encounter the same issue two times in a raw ?

I'll try tomorrow

**Comment by Neo-29** [comment]
> Strange. I installed almost exactly same way. Could you retry same way to see if you encounter the same issue two times in a raw ?

All good after retry.

Perfect.

Closing.
