### ISSUE TITLE
XFS file system choice

### ISSUE THREAD

**Issue by Neo-29** [Rawleenc/ArchCraftsman#81]
Hello,
Could be great having XFS as a choice in addition to:
- EXT4
- BTRFS

Cheers

**Comment by Rawleenc** [comment]
Available on dev branch with few bug fixes and autopart behavior change.

**Comment by Neo-29** [comment]
> Available on dev branch with few bug fixes and autopart behavior change.

I'll test as soon as I can.
Separate `/boot` ext4 partition is an excellent idea to avoid `xfs` issue with grub
