### ISSUE TITLE
Erreur mirroir

### ISSUE THREAD

**Issue by Xdavius** [Rawleenc/ArchCraftsman#82]
Le tri des mirroirs pose problème.

2x lancé l'installation, 2x des paquets en erreur. Mirroir anglais sélectionné et un les autres pas fou.

Ce serait bien de trier mieux les mirroirs (FR/Germany sont souvent plus prorpres). Certains sont vraiment nazes.

de plus, impossible de reprendre l'installation facilement car la conf n'est pas sauvegarer. En cas d'arreur, ce serait bien de pouvoir juste relancer sans tout se retaper inutilement (ou alors une fonction reessayer avec un nouveau reflector ? je sais pas)

merci ! sinon c'est top !

**Comment by Rawleenc** [comment]
Hello !

Le problème du tri des miroir c'est qu'étant donné que le script peux potentiellement être lancé partout dans le monde, il n'y a pas de méthode miracle qui fonctionne à la perfection dans tous les cas et la commande actuellement dans le script semble être une commande qui fonctionne bien dans la plupart des cas.

Donc je ne sais pas trop quoi faire pour améliorer ce point en particulier.

Peut être afficher le résultat du tri et proposer à l'utilisateur de l'éditer lui même s'il le souhaite ?

Pour ce qui est de l'enregistrement de la config en cas d'erreur il y a effectivement quelque chose à faire.

**Comment by Xdavius** [comment]
Hi !

Oui, je pense que l'édition des mirrors à la main après le reflector est une. Bonne idée (j'ai eu un tas de problèmes aujourd'hui de miroirs ! Beaucoup sont mal synchro, ou n'avancent pas).

Une fonction de sauvegarde auto de la configuration avec option chargement de la conf serait bien. Elle se sauvegarde juste avant de s'exécuter. Si on l'a charge, il faudrait la possibilité de la modifier.

Demain je refais un test. J'ai eu pleins de problèmes aujourd'hui.
Je suis entrain de tester le travail de github.com/cardiacman13 pour son script de post install. Et j'ai eu des erreurs fatales (zsh en cause ?)

Merci à toi !

**Comment by Xdavius** [comment]
Bon, j'ai pas de chance XD (version de dev)

![Screenshot_20230922_115614](https://github.com/Rawleenc/ArchCraftsman/assets/66792063/ccfcb2ea-25a1-4e4a-84a8-b9393784671b)

**Comment by Rawleenc** [comment]
Enregistrement de la config réparé. Même en cas d'erreur.

**Comment by Rawleenc** [comment]
Une boucle de vérification et d'édition a été ajouté sur dev.
