### ISSUE TITLE
Clavier EN dans plasma après choix FR

### ISSUE THREAD

**Issue by Xdavius** [Rawleenc/ArchCraftsman#83]
Le clavier n'était pas configurer dans plasma au reboot. Qwerty au lieu de AZERTY

(panneau de conf, clavier, disposition ajouter français)

Pourtant la question est posée (loadkeys fr fait avant install btw)

**Comment by Rawleenc** [comment]
De mon côté le clavier est bien en français, peux tu me transférer le fichier de conf de ton installation plasma ?

**Comment by Rawleenc** [comment]
Par ailleurs j'ai réparé la création du fichier de conf, il devrait maintenant être correctement créé et ceux même en cas d'erreur.

Pense également à enlever du fichier de conf les info sensible telle que les mdp par exemple.

**Comment by Xdavius** [comment]
Je te fais ça rapidement. Je referais une installation propre et je te transmets.

**Comment by Rawleenc** [comment]
Hello @Xdavius 

Je me permet de te relancer sur ce sujet :)

**Comment by Xdavius** [comment]
Je referais une batterie de tests prochainement (j'ai un peu zappé, désolé)

**Comment by Rawleenc** [comment]
Peux tu m'envoyer le fichier de conf ?

**Comment by Rawleenc** [comment]
Peux tu m'envoyer le fichier de conf ?

**Comment by Xdavius** [comment]
> Peux tu m'envoyer le fichier de conf ?

Quel fichier stp ?

**Comment by Xdavius** [comment]
termbin.com/skc8

**Comment by Rawleenc** [comment]
Ok. Le problème vient du faite que tu as choisi `fr` au lieu de `fr-latin9`. Et le Archcraftsman ne reconnait que `fr-latin9` pour la configuration du clavier en FR.

J'ai une idée pour mieux gérer ça.

**Comment by Xdavius** [comment]
> J'ai une idée pour mieux gérer ça.

Cool !

Le mieux c'est fr-latin9 ou fr uniquement ? J'étais resté sur FR a cause du bug de libreoffice avec le pavé numérique, par habitude.

**Comment by Rawleenc** [comment]
Une meilleurs configuration automatique de la locale et du clavier de l'utilisateur est disponible sur dev.

Il s'agit d'une configuration automatique "best effort" basé sur les informations de localisation de l'utilisateur récupéré via l'API https://ipapi.co/json

Les informations récupéré, manipulé et utilisé sont languages et country_code. Ces informations permettent de proposer une configuration des locales ainsi que les keymaps pour console et environnement graphique.

**Comment by Xdavius** [comment]
CA MARCHE AUSSI !
