### ISSUE TITLE
Manque multilib & choix systemd-boot

### ISSUE THREAD

**Issue by Xdavius** [Rawleenc/ArchCraftsman#84]
Bonjour,

ce serait super d'ajouter une option pour activer multilib et le choix entre grub/systemd-boot =) 

Multilib me semble être plus important.

A bientôt !

**Comment by Rawleenc** [comment]
Pour systemd-boot j'y avais déjà réfléchi et c'est trop compliqué, le script est trop conçu autour de grub, un support générique pour d'autre alternative demanderais une refonte trop importante.

Pour multilib par contre c'est possible.

**Comment by Rawleenc** [comment]
Pushed on dev.
