### ISSUE TITLE
Change reflector command

### ISSUE THREAD

**Issue by Rawleenc** [Rawleenc/ArchCraftsman#85]
Following tests, reflector command should be changed by : 
```bash
reflector --verbose -phttps --score 30 --sort rate -a48 --save /etc/pacman.d/mirrorlist
```
Find a solution to detect if ipv6 is available to add `--ipv6` reflector option.

**Comment by Neo-29** [comment]
This is worth trying on my system one day 👍

**Comment by Rawleenc** [comment]
Pushed on dev.
