### ISSUE TITLE
[DEV] Chosir boot ne permet pas de choisir fat (méthode archinstall)

### ISSUE THREAD

**Issue by Xdavius** [Rawleenc/ArchCraftsman#86]
Non bloquant, mais ça peut être un choix. Même si EFI séparé du kernel pour la sécurité en LUKS, c'est mieux ;)

![Screenshot_20231127_114614](https://github.com/Rawleenc/ArchCraftsman/assets/66792063/59067c94-a3dd-4ddb-b92e-c9e1b29050f3)

**Comment by Neo-29** [comment]
Faut la mettre en efi si c'est ta partition boot....

**Comment by Xdavius** [comment]
> Faut la mettre en efi si c'est ta partition boot....

Je sais et l'installateur te met une alerte et te dis : recommence petit con =)

**Comment by Rawleenc** [comment]
Dispo sur dev.

**Comment by Xdavius** [comment]
Ca marche aussi !!!
