### ISSUE TITLE
[Tri des mirroirs] - Erreur avec chroot

### ISSUE THREAD

**Issue by Xdavius** [Rawleenc/ArchCraftsman#87]
Rien a ajouter. Proposer le tri par région ? 
ma commande reflector : reflector --sort score --country [mychoices] --save

c'est la seule où je fail pas. 

![Screenshot_20231127_115411](https://github.com/Rawleenc/ArchCraftsman/assets/66792063/e06fd28f-983e-478f-872d-0e3173f05a05)

**Comment by Xdavius** [comment]
J'ai refait en désactivant le mirroir pourri et c'est passé car si je fais un réflector, ton script lerelance ave sa propre commande et je ne peux pas garder ma conf :(

**Comment by Rawleenc** [comment]
On a vu avec Neo que le filtrage par pays entraine des problème sur certaines connexion

Mais je dois y avoir moyen de proposer ça en option avec les infos de localisation récupérée au début du script

**Comment by Xdavius** [comment]
Voilà la commande réflector que Antiz (Package Mainteneur Arch) nous a transmis : 

reflector --verbose --score 100 --latest 20 --fastest 5 --sort rate --save /etc/pacman.d/mirrorlist

Si ça peu aider.

**Comment by Rawleenc** [comment]
Une meilleurs méthode de tri des miroirs et dispo sur dev.

**Comment by Xdavius** [comment]
NICE !!!!
