### ISSUE TITLE
exfatprog/exfat-utils

### ISSUE THREAD

**Issue by Xdavius** [Rawleenc/ArchCraftsman#88]
Tu choisis d'installer exfatprobs, et arch exfat-utils.

Une différence évidente entre les deux ou pas du tout ? (c'est plus par curiosité)

**Comment by Rawleenc** [comment]
exfatprogs a l'air d'être un ensemble d'outils userspace récent existant depuis le merge de ExFAT dans le noyau 5.7 (https://github.com/exfatprogs/exfatprogs).

exfat-utils est un paquet "legacy" mais qui a l'air d'être encore maintenu (https://github.com/relan/exfat), c'était l'implémentation complète de ExFAT pour linux avant le merge. Donc je pourrais probablement supprimer exfat-utils du bundle des système de fichiers principaux mais il faudrait tester et je n'utilise plus ExFAT depuis un moment.
